Repository SourenP/ungroup_game, pull requests merged in 2020-02, with the labels that each got.

#174 Uniq win
  src/client/rendering/BaseUIElement.hpp
  src/client/rendering/RenderingDef.hpp
  src/client/rendering/ResourceUIElement.cpp
  src/client/rendering/ResourceUIElement.hpp
  src/client/systems/ClientGameController.cpp
  src/common/CMakeLists.txt
  src/common/models/WinCondition.cpp
  src/common/models/WinCondition.hpp
  src/common/objects/Player.cpp
  src/common/objects/Player.hpp
  src/common/systems/GameObjectController.cpp
Labels: feature, graphics

#179 Make voronoi count shader work with low cell count
  resources/shaders/voronoi_counts.frag
  src/client/rendering/DrawableMine.cpp
  src/client/rendering/RenderingDef.hpp
Labels: graphics, performance

#180 Load game settings from config at runtime
  CMakeLists.txt
  data/configs/game_settings.json
  extern/nlohmann/json.hpp
  src/client/main.cpp
  src/client/rendering/BackgroundController.cpp
  src/client/rendering/DirectionArrows.cpp
  src/client/rendering/RenderingController.cpp
  src/client/rendering/RenderingDef.hpp
  src/client/systems/ClientGameController.cpp
  src/client/systems/ClientGameController.hpp
  src/client/systems/NetworkingClient.cpp
  src/common/CMakeLists.txt
  src/common/bots/Bot.cpp
  src/common/objects/Mine.cpp
  src/common/objects/Mine.hpp
  src/common/physics/PhysicsController.cpp
  src/common/systems/GameObjectStore.cpp
  src/common/systems/GroupController.cpp
  src/common/systems/LevelController.cpp
  src/common/util/game_settings.cpp
  src/common/util/game_settings.hpp
  src/server/main.cpp
  src/server/systems/NetworkingServer.cpp
Labels: build, code quality

#182 Remove gperftools
  .travis.yml
  CMakeLists.txt
  src/client/CMakeLists.txt
  src/server/CMakeLists.txt
Labels: build

#183 Sync player intent over network and set direction arrow to intent color
  src/client/rendering/DirectionArrows.cpp
  src/client/rendering/DirectionArrows.hpp
  src/client/rendering/DrawableGroup.cpp
  src/client/rendering/DrawableGroup.hpp
  src/client/rendering/RenderingDef.hpp
  src/common/objects/Player.cpp
  src/common/objects/Player.hpp
Labels: enhancement, graphics
